# stages:
#   - build
before_script:
    - az login --service-principal -u $DAGGERSP_APPID -p $DAGGERSP_SECRET --tenant $DAGGERSP_TENANT
    - az account set --subscription $AZURE_SUBSCRIPTION_ID
    - az acr login --name dagger  

variables:
  TAG: "1.4.$CI_PIPELINE_IID"
  REGISTRY_HOST: ${{ secrets.REGISTRY_HOST }}
  CLIENTID: ${{ secrets.CLIENTID }}
  CLIENTSECRET: ${{ secrets.CLIENTSECRET }}
  TENANTID: ${{ secrets.TENANTID }}
  KVPATH: ${{ secrets.KVPATH }}

.docker:
  image: dagger.azurecr.io/golang-azcli
  services:
    - docker:${DOCKER_VERSION}-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_VERIFY: '1'
    DOCKER_TLS_CERTDIR: '/certs'
    DOCKER_CERT_PATH: '/certs/client'
    DOCKER_DRIVER: overlay2
    DOCKER_VERSION: '20.10.16'
.dagger:
  extends: [.docker]
  before_script:
    - echo "TAG=$TAG"
    # - apk add --no-cache docker-cli curl tar openssl sudo bash jq python3 py3-pip git
    # - apk --update --upgrade add gcc musl-dev libffi-dev openssl-dev make python3-dev
    # - python3 -m venv venv
    # - source venv/bin/activate
    # - pip install --upgrade pip
    # - pip install azure-cli
    # - cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sh; cd -; }
    # - curl -LO https://github.com/sigstore/cosign/releases/download/v1.4.1/cosign-linux-amd64
    # - chmod +x cosign-linux-amd64
    # - mv cosign-linux-amd64 /usr/local/bin/cosign


    # - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
.commit:
  extends: [.dagger]
  script:
    - dagger run go run dagger/main-gitlab.go
    # - apk add --no-cache curl
    - cosign sign -a commit=$CI_COMMIT_SHA -key $KVPATH $REGISTRY_HOST/dagger:$TAG
    - git config --local user.email "gitlab-ci[bot]@users.noreply.gitlab.com"
    - git config --local user.name "gitlab-ci[bot]"
    - git add .
    - git commit -m "Release $TAG [skip ci]"
    - git push origin HEAD:$CI_COMMIT_REF_NAME
    
  only:
    - main
    - master
  variables:
    COSIGN_PRIVATE_KEY: $COSIGN_PRIVATE_KEY
    COSIGN_PASSWORD: $COSIGN_PASSWORD
    ACR_REGISTRY_PASSWORD: $ACR_REGISTRY_PASSWORD
    TENANTID: $TENANTID
    REGISTRY_HOST: $REGISTRY_HOST
    CLIENTID: $CLIENTID
    CLIENTSECRET: $CLIENTSECRET
    KVPATH: $KVPATH 

build:
  extends: .commit