# stages:
#   - build
# before_script:
#     - az login --service-principal -u $DAGGERSP_APPID -p $DAGGERSP_SECRET --tenant $DAGGERSP_TENANT
#     - az account set --subscription $AZURE_SUBSCRIPTION_ID
#     - az acr login --name dagger  

  # image: mcr.microsoft.com/azure-cli
  # before_script:
  #   - echo "TAG=$TAG"
  #   - az login --service-principal -u $AZURE_APP_ID -p $AZURE_PASSWORD --tenant $AZURE_TENANT_ID
  #   - az account set --subscription $AZURE_SUBSCRIPTION_ID
  #   - az acr login --name dagger --expose-token

variables:
  TAG: "1.4.$CI_PIPELINE_IID"
  ACR_REGISTRY_PASSWORD: $ACR_REGISTRY_PASSWORD
  AZURE_TENANT_ID: $AZURE_TENANT_ID
  REGISTRY_HOST: $REGISTRY_HOST
  AZURE_APP_ID: $AZURE_APP_ID
  AZURE_PASSWORD: $AZURE_PASSWORD
  AZURE_SUBSCRIPTION_ID: $AZURE_SUBSCRIPTION_ID
  DAGGER_APPID: $DAGGER_APPID
  DAGGER_SECRET: $DAGGER_SECRET
  DAGGER_TENANT: $DAGGER_TENANT
  DOCKERHUB_TOKEN: $DOCKERHUB_TOKEN
  # REGISTRY_HOST: ${{ secrets.REGISTRY_HOST }}
  # CLIENTID: ${{ secrets.CLIENTID }}
  # CLIENTSECRET: ${{ secrets.CLIENTSECRET }}
  # TENANTID: ${{ secrets.TENANTID }}
  # KVPATH: ${{ secrets.KVPATH }}

.azure-cli:
  # image: mcr.microsoft.com/azure-cli
  before_script:
    - echo "TAG=$TAG"
    - az login --service-principal -u $AZURE_APP_ID -p $AZURE_PASSWORD --tenant $AZURE_TENANT_ID
    - az account set --subscription $AZURE_SUBSCRIPTION_ID
    # - az acr login --name dagger --expose-token
    - docker login  -u davidgardiner -p ${DOCKERHUB_TOKEN}
    
.docker:
  # image: dagger.azurecr.io/goland-azcli:0.1
  # image: golang:alpine
  image: davidgardiner/golang-azcli:0.1
  extends: [.azure-cli]
  # image: dagger.azurecr.io/golang-azcli:latest
  # image: dagger.azurecr.io/goland-azcli:0.1
  before_script:
    - echo "TAG=$TAG"
    # - az login --service-principal -u $AZURE_APP_ID -p $AZURE_PASSWORD --tenant $AZURE_TENANT_ID
    # - az login --service-principal -u $DAGGER_APPID -p $DAGGER_SECRET --tenant $DAGGER_TENANT
    # - docker login dagger.azurecr.io -u xdagger -p myPassword $ACR_REGISTRY_PASSWORD
    # - az account set --subscription $AZURE_SUBSCRIPTION_ID
    # - az acr login --name dagger --username dagger --password $ACR_REGISTRY_PASSWORD --expose-token
  services:
    - docker:${DOCKER_VERSION}-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_VERIFY: '1'
    DOCKER_TLS_CERTDIR: '/certs'
    DOCKER_CERT_PATH: '/certs/client'
    DOCKER_DRIVER: overlay2
    DOCKER_VERSION: '20.10.16'




    # - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
.commit:
  # image: dagger.azurecr.io/goland-azcli:0.1
  extends: [.docker]
  script:
    # - apk add --no-cache docker-cli curl tar openssl sudo bash jq python3 py3-pip git
    # - apk --update --upgrade add gcc musl-dev libffi-dev openssl-dev make python3-dev
    # - python3 -m venv venv
    # - source venv/bin/activate
    # - pip install --upgrade pip
    # - pip install azure-cli
    - cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sh; cd -; }
    - curl -LO https://github.com/sigstore/cosign/releases/download/v1.4.1/cosign-linux-amd64
    - chmod +x cosign-linux-amd64
    - mv cosign-linux-amd64 /usr/local/bin/cosign
    - docker login  -u davidgardiner -p ${DOCKERHUB_TOKEN}
    - dagger run go run dagger/main-gitlab.go
    - az login --service-principal -u $AZURE_APP_ID -p $AZURE_PASSWORD --tenant $AZURE_TENANT_ID
    - az account set --subscription $AZURE_SUBSCRIPTION_ID
    - cosign sign -a commit=$CI_COMMIT_SHA -key $KVPATH davidgardiner/dagger:$TAG
    - git config --local user.email "gitlab-ci[bot]@users.noreply.gitlab.com"
    - git config --local user.name "gitlab-ci[bot]"
    - git add .
    - git commit -m "Release $TAG [skip ci]"
    - git push origin HEAD:$CI_COMMIT_REF_NAME
    
  only:
    - main
    - master
  variables:
    COSIGN_PRIVATE_KEY: $COSIGN_PRIVATE_KEY
    COSIGN_PASSWORD: $COSIGN_PASSWORD
    ACR_REGISTRY_PASSWORD: $ACR_REGISTRY_PASSWORD
    TENANTID: $TENANTID
    REGISTRY_HOST: $REGISTRY_HOST
    CLIENTID: $CLIENTID
    CLIENTSECRET: $CLIENTSECRET
    KVPATH: $KVPATH 

build:
  extends: .commit