project: dot
providers:
  google_secretmanager:
    env:
      COSIGN_PRIVATE_KEY:
        path: projects/davidmarkgardiner/secrets/cosign/versions/1
      COSIGN_PASSWORD:
        path: projects/davidmarkgardiner/secrets/cosign-password/versions/1
      REGISTRY_PASSWORD:
        path: projects/davidmarkgardiner/secrets/c8n-secret/versions/1
