stages:
  - build

variables:
  REGISTRY_HOST: ${{ secrets.REGISTRY_HOST }}
  CLIENTID: ${{ secrets.CLIENTID }}
  CLIENTSECRET: ${{ secrets.CLIENTSECRET }}
  TENANTID: ${{ secrets.TENANTID }}
  KVPATH: ${{ secrets.KVPATH }}


build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CLIENTID -p $CLIENTSECRET $REGISTRY_HOST
    - docker build -t $REGISTRY_HOST/hello-world:latest .
    - docker push $REGISTRY_HOST/hello-world:latest
    - apk add --no-cache curl
    - curl -LO https://github.com/sigstore/cosign/releases/download/v1.4.1/cosign-linux-amd64
    - chmod +x cosign-linux-amd64
    - mv cosign-linux-amd64 /usr/local/bin/cosign
    - cosign sign -a commit=$CI_COMMIT_SHA -key $KVPATH $REGISTRY_HOST/hello-world:latest
  only:
    - main
    - merge_requests
  tags:
    - docker