image:
  repository: c8n.io/vfarcic/silly-demo
  tag: 1.4.100
ingress:
  host: devopstoolkitseries.com
db:
  enabled: false
postgresql:
  global:
    persistence:
      enabled: false
  auth:
    postgresPassword: postgres
  primary:
    initdb:
      scripts:
        00_init_script.sh: |
          export PGPASSWORD=$POSTGRES_PASSWORD
          psql -U postgres -c 'CREATE DATABASE "silly-demo";'
schemahero:
  enabled: false
